# Generated by Django 2.1.7 on 2019-03-24 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0002_auto_20190324_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amt', models.PositiveIntegerField()),
                ('payment_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('rating', models.PositiveIntegerField()),
                ('left_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.CharField(default='Norwich', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Item'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='renter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renter_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviews',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='job_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.JobList'),
        ),
        migrations.AddField(
            model_name='job',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
    ]
