# Generated by Django 2.1.7 on 2019-03-25 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0003_auto_20190324_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('additional_info', models.CharField(blank=True, max_length=500)),
                ('cost_per_day', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost_per_day',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='region',
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='item_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Item'),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
