# Generated by Django 2.1.7 on 2019-03-25 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0005_itemcategorypair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='left_by_user',
            new_name='left_by_user_id',
        ),
        migrations.AlterField(
            model_name='dispute',
            name='transaction_id',
            field=models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Category'),
        ),
        migrations.AlterField(
            model_name='itemcategorypair',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Category'),
        ),
        migrations.AlterField(
            model_name='itemcategorypair',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Item'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='item_type_id',
            field=models.ForeignKey(db_column='item_type_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Item'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_list_id',
            field=models.ForeignKey(db_column='job_list_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.JobList'),
        ),
        migrations.AlterField(
            model_name='job',
            name='transaction_id',
            field=models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='staff_id',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='left_by_user_id',
            field=models.ForeignKey(db_column='left_by_user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='transaction_id',
            field=models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Item'),
        ),
    ]
