# Generated by Django 2.1.7 on 2019-03-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0007_auto_20190325_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_id',
        ),
    ]
