# Generated by Django 2.1.7 on 2019-03-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0008_remove_item_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Staff'), ('A', 'Admin')], default='Customer', max_length=50),
        ),
    ]
