# Generated by Django 2.1.7 on 2019-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0010_auto_20190326_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
