# Generated by Django 2.1.7 on 2019-03-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0011_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='card_long_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
