# Generated by Django 2.1.7 on 2019-03-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0013_job_due_delivery_datetime'),
        ('rentalsystem', '0012_profile'),
    ]

    operations = [
    ]
