# Generated by Django 2.1.7 on 2019-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0014_merge_20190327_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, default='defaut.png', max_length=100),
            preserve_default=False,
        ),
    ]
