# Generated by Django 2.1.7 on 2019-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0016_auto_20190327_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
    ]
