# Generated by Django 2.1.7 on 2019-04-17 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0017_auto_20190414_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('address2', models.CharField(blank=True, max_length=200, null=True)),
                ('address3', models.CharField(blank=True, max_length=200, null=True)),
                ('address4', models.CharField(blank=True, max_length=200, null=True)),
                ('address5', models.CharField(blank=True, max_length=200, null=True)),
                ('county', models.CharField(max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(db_column='CustomUser_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='address3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='address4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='address5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='county',
            field=models.CharField(default='Norfolk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
