# Generated by Django 2.1.7 on 2019-05-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0023_auto_20190513_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Address'),
        ),
    ]
