# Generated by Django 2.1.7 on 2019-05-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0025_remove_address_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(db_column='address_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Address'),
            preserve_default=False,
        ),
    ]
