# Generated by Django 2.2.1 on 2019-05-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0027_auto_20190513_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lowest_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
