# Generated by Django 2.1.7 on 2019-05-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0027_auto_20190513_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='transaction_id',
            field=models.ForeignKey(db_column='transaction_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='rentalsystem.Transaction'),
        ),
    ]
