# Generated by Django 2.1.7 on 2019-05-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsystem', '0028_auto_20190514_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
